### ISSUE TITLE
All about trees

### ISSUE THREAD

**Issue by MMikhailova** [lab-brussels-1/The-first-group#1]
- [ ] [repo](https://github.com/lab-brussels-1/The-first-group-) 
- [ ] [live demo](https://lab-brussels-1.github.io/The-first-group-/)
- [/planning](https://github.com/_/_/tree/master/planning)
  - [ ] constraints
  - [ ] communication plan
  - [ ] user personas
  - [ ] backlog
  - [ ] design
  - [ ] development strategy
  - [ ] retrospective
- [ ] [project board](https://github.com/_/_/projects/1)

**Comment by talmurshidi** [comment]
Hello @MMikhailova 
I hope to create deliverable in the right place like this [Group-2: Agile Development 4 weeks](https://github.com/lab-brussels-1/home/issues/209) and the name Group-1: Agile Development week 1
