### ISSUE TITLE
Communication Plan

### ISSUE THREAD

**Issue by MMikhailova** [lab-brussels-1/The-first-group#6]
In this step we create a communication plan for the project:

- [x] Add availability.
- [x] Add how many hours has per day.

**Comment by talmurshidi** [comment]
Creating a separate issue for each team member is better approach and more flexible.
`One issue belongs to one PR`.
When closing the PR, the issue will be closed with it.
You can create issue for each member ex: `Tamer communication plan` and the details could be:
[/planning/communication.md](https://github.com/lab-brussels-1/The-first-group/blob/master/planning/communication-plan.md)
- [ ] Add availability.
- [ ] Add how many hours has per day.

**Comment by MMikhailova** [comment]
@talmurshidi Should  we create a new branch for each issue as well ex: maria_communication, maria_development and etc.?

**Comment by talmurshidi** [comment]
@MMikhailova 
Yes, each one will create a new branch to solve his/her issue.
